

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
  
  drift:
    depends_on:
      - mosquitto
    container_name: drift
    build:
      context: ./data-orchestation
      dockerfile: Base.Dockerfile
      args: 
        CMD: drift
  
  exporter:
    depends_on:
      - mosquitto
    container_name: exporter
    build:
      context: ./data-orchestation
      dockerfile: Base.Dockerfile
      args: 
        CMD: exporter
    ports:
      -  8000:8000
    environment:
      - INFLUX_URI=http://influxdb2:8086
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=ut

  turtle:
    container_name: turtle
    build:
      context: ./data-orchestation
      dockerfile: Base.Dockerfile
      args: 
        CMD: turtle
    ports:
      -  50051:50051

  controller:
    depends_on:
      - mosquitto
      - turtle
      - database
    container_name: controller
    build:
      context: ./data-orchestation
      dockerfile: Base.Dockerfile
      args: 
        CMD: controller
    environment:
      - INFLUX_URI=http://influxdb2:8086
      - INFLUX_TOKEN=my-super-secret-auth-token
      - INFLUX_ORG=ut
      - SLACK_TOKEN=${SLACK_TOKEN} #TODO
      - SLACK_CHANNEL_ID=${SLACK_CHANNEL_ID} #TODO
      - TURTLE_IP_ADDRESS=turtle:50051 #TODO
      - ACTIONS_HOST=database
      - ACTIONS_USERNAME=admin
      - ACTIONS_PASSWORD=Asdf1234
      - ACTIONS_DB=actions
      - ACTIONS_PORT=5432
  
  database:
    container_name: database
    image: postgres
    restart: always
    ports:
      -  5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Asdf1234
      - POSTGRES_DB=actions
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
  
  adminer:
    depends_on:
      - database
    image: adminer
    restart: always
    ports:
      - 8080:8080

  influxdb2:
    container_name: influxdb2
    image: influxdb:2
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=Asdf1234
      - DOCKER_INFLUXDB_INIT_ORG=ut
      - DOCKER_INFLUXDB_INIT_BUCKET=stations
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb-data:/var/lib/influxdb2

  telegraf:
    depends_on:
      - influxdb2
    container_name: telegraf
    image: telegraf
    ports:
      - 8125:8125
      - 8092:8092
      - 8094:8094
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
  influxdb-data:
  mosquitto-data:
  pg-data: