# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: agent.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61gent.proto\x12\x05\x61gent\" \n\x0bMoveCommand\x12\x11\n\tstationId\x18\x01 \x01(\t\"\'\n\x08Response\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07onError\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"S\n\x06Status\x12 \n\x05state\x18\x01 \x01(\x0e\x32\x11.agent.AgentState\x12\x11\n\tstationId\x18\x02 \x01(\t\x12\x14\n\x0c\x62\x61tteryState\x18\x03 \x01(\x02*G\n\nAgentState\x12\x0e\n\nIN_TRANSIT\x10\x00\x12\x0e\n\nIN_STATION\x10\x01\x12\x0b\n\x07IN_BASE\x10\x02\x12\x0c\n\x08ON_ERROR\x10\x03\x32q\n\x0c\x41gentControl\x12\x34\n\rMoveToStation\x12\x12.agent.MoveCommand\x1a\x0f.agent.Response\x12+\n\x0cReportStatus\x12\x0c.agent.Empty\x1a\r.agent.StatusB;Z9github.com/JuanGQCadavid/co2_station/data-orchestation/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/JuanGQCadavid/co2_station/data-orchestation/pb'
  _globals['_AGENTSTATE']._serialized_start=191
  _globals['_AGENTSTATE']._serialized_end=262
  _globals['_MOVECOMMAND']._serialized_start=22
  _globals['_MOVECOMMAND']._serialized_end=54
  _globals['_RESPONSE']._serialized_start=56
  _globals['_RESPONSE']._serialized_end=95
  _globals['_EMPTY']._serialized_start=97
  _globals['_EMPTY']._serialized_end=104
  _globals['_STATUS']._serialized_start=106
  _globals['_STATUS']._serialized_end=189
  _globals['_AGENTCONTROL']._serialized_start=264
  _globals['_AGENTCONTROL']._serialized_end=377
# @@protoc_insertion_point(module_scope)
